baseurl = "https://msfjarvis.me/"
googleAnalytics = "UA-XXXXX-Y"
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Harsh Shandilya"

[params]
  appletouchicon = "apple-touch-icon-precomposed.png"
  avatar = "harsh.jpg"
  background = "bg1.jpg"
  email = "msfjarvis@gmail.com"
  favicon = "favicon.ico"
  name = "Harsh Shandilya"
  position = "Mobile Build Engineer"
  [params.contact]
    buttonText = "Send it"
    emailPlaceholder = "Email"
    enable = true
    formTitle = "Touch Me!"
    messagePlaceholder = "Message"
    namePlaceholder = "Name"
  [params.footer]
    copyright = "Harsh Shandilya"

  [[params.social]]
    icon = "fa-twitter"
    link = "https://twitter.com/MSF_Jarvis"
    title = "Twitter"

  [[params.social]]
    icon = "fa-github"
    link = "https://github.com/MSF-Jarvis"
    title = "Github"

  [[params.social]]
    icon = "fa-rss"
    link = "https://blog.msfjarvis.me"
    title = "Blog"

